trigger:
- '*' # main or other git branches
stages:
- stage: 'Dev'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Test'
    displayName: 'echo hello world'
    pool: #
      vmImage: 'ubuntu-20.04'
    steps:
    - bash: echo hello world